"use strict";
exports.__esModule = true;
exports.G1CurveEnum = exports.VerificationMethodDescriptorUserVerificationMethodEnum = exports.operatingEnvEnum = exports.tcDisplayContentTypeEnum = exports.attestationTypesEnum = exports.publicKeyAlgAndEncodingsEnum = exports.authenticationAlgorithmsEnum = exports.protocolFamilyEnum = exports.keyProtectionEnum = exports.matcherProtectionEnum = exports.attachmentHintEnum = exports.tcDisplayEnum = exports.assertionSchemeEnum = exports.V2FunctionName = exports.V3FunctionName = void 0;
var V3FunctionName;
(function (V3FunctionName) {
    V3FunctionName[V3FunctionName["aaid"] = 1] = "aaid";
    V3FunctionName[V3FunctionName["aaguid"] = 2] = "aaguid";
    V3FunctionName[V3FunctionName["attestationCertificateKeyIdentifiers"] = 3] = "attestationCertificateKeyIdentifiers";
    V3FunctionName[V3FunctionName["authenticatorVersion"] = 4] = "authenticatorVersion";
    V3FunctionName[V3FunctionName["protocolFamily"] = 5] = "protocolFamily";
    V3FunctionName[V3FunctionName["schema"] = 6] = "schema";
    V3FunctionName[V3FunctionName["upv"] = 7] = "upv";
    V3FunctionName[V3FunctionName["authenticationAlgorithms"] = 8] = "authenticationAlgorithms";
    V3FunctionName[V3FunctionName["publicKeyAlgAndEncodings"] = 9] = "publicKeyAlgAndEncodings";
    V3FunctionName[V3FunctionName["attestationTypes"] = 10] = "attestationTypes";
    V3FunctionName[V3FunctionName["userVerificationDetails"] = 11] = "userVerificationDetails";
    V3FunctionName[V3FunctionName["keyProtection"] = 12] = "keyProtection";
    V3FunctionName[V3FunctionName["matcherProtection"] = 13] = "matcherProtection";
    V3FunctionName[V3FunctionName["cryptoStrength"] = 14] = "cryptoStrength";
    V3FunctionName[V3FunctionName["attachmentHint"] = 15] = "attachmentHint";
    V3FunctionName[V3FunctionName["tcDisplay"] = 16] = "tcDisplay";
    V3FunctionName[V3FunctionName["tcDisplayContentType"] = 17] = "tcDisplayContentType";
    V3FunctionName[V3FunctionName["tcDisplayPNGCharacteristics"] = 18] = "tcDisplayPNGCharacteristics";
    V3FunctionName[V3FunctionName["attestationRootCertificates"] = 19] = "attestationRootCertificates";
    V3FunctionName[V3FunctionName["ecdaaTrustAnchors"] = 20] = "ecdaaTrustAnchors";
    V3FunctionName[V3FunctionName["icon"] = 21] = "icon";
    V3FunctionName[V3FunctionName["authenticatorGetInfo"] = 22] = "authenticatorGetInfo";
    //supportedExtensions = 23,
})(V3FunctionName = exports.V3FunctionName || (exports.V3FunctionName = {}));
var V2FunctionName;
(function (V2FunctionName) {
    V2FunctionName[V2FunctionName["aaid"] = 1] = "aaid";
    V2FunctionName[V2FunctionName["aaguid"] = 2] = "aaguid";
    V2FunctionName[V2FunctionName["attestationCertificateKeyIdentifiers"] = 3] = "attestationCertificateKeyIdentifiers";
    V2FunctionName[V2FunctionName["authenticatorVersion"] = 4] = "authenticatorVersion";
    V2FunctionName[V2FunctionName["protocolFamily"] = 5] = "protocolFamily";
    V2FunctionName[V2FunctionName["upv"] = 6] = "upv";
    V2FunctionName[V2FunctionName["assertionScheme"] = 7] = "assertionScheme";
    V2FunctionName[V2FunctionName["authenticationAlgorithm"] = 8] = "authenticationAlgorithm";
    V2FunctionName[V2FunctionName["authenticationAlgorithms"] = 9] = "authenticationAlgorithms";
    V2FunctionName[V2FunctionName["publicKeyAlgAndEncoding"] = 10] = "publicKeyAlgAndEncoding";
    V2FunctionName[V2FunctionName["publicKeyAlgAndEncodings"] = 11] = "publicKeyAlgAndEncodings";
    V2FunctionName[V2FunctionName["attestationTypes"] = 12] = "attestationTypes";
    V2FunctionName[V2FunctionName["userVerificationDetails"] = 13] = "userVerificationDetails";
    V2FunctionName[V2FunctionName["keyProtection"] = 14] = "keyProtection";
    V2FunctionName[V2FunctionName["matcherProtection"] = 15] = "matcherProtection";
    V2FunctionName[V2FunctionName["cryptoStrengthCeck"] = 16] = "cryptoStrengthCeck";
    V2FunctionName[V2FunctionName["operatingEnv"] = 17] = "operatingEnv";
    V2FunctionName[V2FunctionName["attachmentHint"] = 18] = "attachmentHint";
    V2FunctionName[V2FunctionName["tcDisplay"] = 19] = "tcDisplay";
    V2FunctionName[V2FunctionName["tcDisplayContentType"] = 20] = "tcDisplayContentType";
    V2FunctionName[V2FunctionName["tcDisplayPNGCharacteristics"] = 21] = "tcDisplayPNGCharacteristics";
    V2FunctionName[V2FunctionName["attestationRootCertificates"] = 22] = "attestationRootCertificates";
    V2FunctionName[V2FunctionName["ecdaaTrustAnchors"] = 23] = "ecdaaTrustAnchors";
    V2FunctionName[V2FunctionName["icon"] = 24] = "icon";
    //supportedExtensions = 25,   
})(V2FunctionName = exports.V2FunctionName || (exports.V2FunctionName = {}));
var assertionSchemeEnum;
(function (assertionSchemeEnum) {
    assertionSchemeEnum[assertionSchemeEnum["U2FV1BIN"] = 0] = "U2FV1BIN";
    assertionSchemeEnum[assertionSchemeEnum["FIDOV2"] = 1] = "FIDOV2";
    assertionSchemeEnum[assertionSchemeEnum["UAFV1TLV"] = 2] = "UAFV1TLV";
})(assertionSchemeEnum = exports.assertionSchemeEnum || (exports.assertionSchemeEnum = {}));
var tcDisplayEnum;
(function (tcDisplayEnum) {
    tcDisplayEnum[tcDisplayEnum["any"] = 0] = "any";
    tcDisplayEnum[tcDisplayEnum["privileged_software"] = 1] = "privileged_software";
    tcDisplayEnum[tcDisplayEnum["tee"] = 2] = "tee";
    tcDisplayEnum[tcDisplayEnum["hardware"] = 3] = "hardware";
    tcDisplayEnum[tcDisplayEnum["remote"] = 4] = "remote";
})(tcDisplayEnum = exports.tcDisplayEnum || (exports.tcDisplayEnum = {}));
var attachmentHintEnum;
(function (attachmentHintEnum) {
    attachmentHintEnum[attachmentHintEnum["internal"] = 0] = "internal";
    attachmentHintEnum[attachmentHintEnum["external"] = 1] = "external";
    attachmentHintEnum[attachmentHintEnum["wired"] = 2] = "wired";
    attachmentHintEnum[attachmentHintEnum["wireless"] = 3] = "wireless";
    attachmentHintEnum[attachmentHintEnum["nfc"] = 4] = "nfc";
    attachmentHintEnum[attachmentHintEnum["bluetooth"] = 5] = "bluetooth";
    attachmentHintEnum[attachmentHintEnum["network"] = 6] = "network";
    attachmentHintEnum[attachmentHintEnum["ready"] = 7] = "ready";
    attachmentHintEnum[attachmentHintEnum["wifi_direct"] = 8] = "wifi_direct";
})(attachmentHintEnum = exports.attachmentHintEnum || (exports.attachmentHintEnum = {}));
var matcherProtectionEnum;
(function (matcherProtectionEnum) {
    matcherProtectionEnum[matcherProtectionEnum["software"] = 0] = "software";
    matcherProtectionEnum[matcherProtectionEnum["tee"] = 1] = "tee";
    matcherProtectionEnum[matcherProtectionEnum["on_chip"] = 2] = "on_chip";
})(matcherProtectionEnum = exports.matcherProtectionEnum || (exports.matcherProtectionEnum = {}));
var keyProtectionEnum;
(function (keyProtectionEnum) {
    keyProtectionEnum[keyProtectionEnum["software"] = 0] = "software";
    keyProtectionEnum[keyProtectionEnum["hardware"] = 1] = "hardware";
    keyProtectionEnum[keyProtectionEnum["tee"] = 2] = "tee";
    keyProtectionEnum[keyProtectionEnum["secure_element"] = 3] = "secure_element";
    keyProtectionEnum[keyProtectionEnum["remote_handle"] = 4] = "remote_handle";
})(keyProtectionEnum = exports.keyProtectionEnum || (exports.keyProtectionEnum = {}));
var protocolFamilyEnum;
(function (protocolFamilyEnum) {
    protocolFamilyEnum[protocolFamilyEnum["uaf"] = 0] = "uaf";
    protocolFamilyEnum[protocolFamilyEnum["u2f"] = 1] = "u2f";
    protocolFamilyEnum[protocolFamilyEnum["fido2"] = 2] = "fido2";
})(protocolFamilyEnum = exports.protocolFamilyEnum || (exports.protocolFamilyEnum = {}));
//errore documentazione: 0x000B == 0x003 (solo nome tra virgolette)
var authenticationAlgorithmsEnum;
(function (authenticationAlgorithmsEnum) {
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp256r1_ecdsa_sha256_raw"] = 0] = "secp256r1_ecdsa_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp256r1_ecdsa_sha256_der"] = 1] = "secp256r1_ecdsa_sha256_der";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pss_sha256_raw"] = 2] = "rsassa_pss_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pss_sha256_der"] = 3] = "rsassa_pss_sha256_der";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp256k1_ecdsa_sha256_raw"] = 4] = "secp256k1_ecdsa_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp256k1_ecdsa_sha256_der"] = 5] = "secp256k1_ecdsa_sha256_der";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["sm2_sm3_raw"] = 6] = "sm2_sm3_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsa_emsa_pkcs1_sha256_raw"] = 7] = "rsa_emsa_pkcs1_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsa_emsa_pkcs1_sha256_der"] = 8] = "rsa_emsa_pkcs1_sha256_der";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pss_sha384_raw"] = 9] = "rsassa_pss_sha384_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pss_sha512_raw"] = 10] = "rsassa_pss_sha512_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pkcsv15_sha256_raw"] = 11] = "rsassa_pkcsv15_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pkcsv15_sha384_raw"] = 12] = "rsassa_pkcsv15_sha384_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pkcsv15_sha512_raw"] = 13] = "rsassa_pkcsv15_sha512_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["rsassa_pkcsv15_sha1_raw"] = 14] = "rsassa_pkcsv15_sha1_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp384r1_ecdsa_sha384_raw"] = 15] = "secp384r1_ecdsa_sha384_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["secp512r1_ecdsa_sha256_raw"] = 16] = "secp512r1_ecdsa_sha256_raw";
    authenticationAlgorithmsEnum[authenticationAlgorithmsEnum["ed25519_eddsa_sha512_raw"] = 17] = "ed25519_eddsa_sha512_raw";
})(authenticationAlgorithmsEnum = exports.authenticationAlgorithmsEnum || (exports.authenticationAlgorithmsEnum = {}));
var publicKeyAlgAndEncodingsEnum;
(function (publicKeyAlgAndEncodingsEnum) {
    publicKeyAlgAndEncodingsEnum[publicKeyAlgAndEncodingsEnum["ecc_x962_raw"] = 0] = "ecc_x962_raw";
    publicKeyAlgAndEncodingsEnum[publicKeyAlgAndEncodingsEnum["ecc_x962_der"] = 1] = "ecc_x962_der";
    publicKeyAlgAndEncodingsEnum[publicKeyAlgAndEncodingsEnum["rsa_2048_raw"] = 2] = "rsa_2048_raw";
    publicKeyAlgAndEncodingsEnum[publicKeyAlgAndEncodingsEnum["rsa_2048_der"] = 3] = "rsa_2048_der";
    publicKeyAlgAndEncodingsEnum[publicKeyAlgAndEncodingsEnum["cose"] = 4] = "cose";
})(publicKeyAlgAndEncodingsEnum = exports.publicKeyAlgAndEncodingsEnum || (exports.publicKeyAlgAndEncodingsEnum = {}));
var attestationTypesEnum;
(function (attestationTypesEnum) {
    attestationTypesEnum[attestationTypesEnum["basic_full"] = 0] = "basic_full";
    attestationTypesEnum[attestationTypesEnum["basic_surrogate"] = 1] = "basic_surrogate";
    attestationTypesEnum[attestationTypesEnum["ecdaa"] = 2] = "ecdaa";
    attestationTypesEnum[attestationTypesEnum["attca"] = 3] = "attca";
})(attestationTypesEnum = exports.attestationTypesEnum || (exports.attestationTypesEnum = {}));
var tcDisplayContentTypeEnum;
(function (tcDisplayContentTypeEnum) {
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["application/octet-stream"] = 0] = "application/octet-stream";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["application/postscript"] = 1] = "application/postscript";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["message/external-body"] = 2] = "message/external-body";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["message/rfc822"] = 3] = "message/rfc822";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["audio/basic"] = 4] = "audio/basic";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["image/jpeg"] = 5] = "image/jpeg";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["image/gif"] = 6] = "image/gif";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["image/png"] = 7] = "image/png";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["text/enriched"] = 8] = "text/enriched";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["text/plain"] = 9] = "text/plain";
    tcDisplayContentTypeEnum[tcDisplayContentTypeEnum["text/foo"] = 10] = "text/foo";
})(tcDisplayContentTypeEnum = exports.tcDisplayContentTypeEnum || (exports.tcDisplayContentTypeEnum = {}));
var operatingEnvEnum;
(function (operatingEnvEnum) {
    operatingEnvEnum[operatingEnvEnum["TEEs based on ARM TrustZone HW"] = 0] = "TEEs based on ARM TrustZone HW";
    operatingEnvEnum[operatingEnvEnum["TEE Based on Intel VT HW"] = 1] = "TEE Based on Intel VT HW";
    operatingEnvEnum[operatingEnvEnum["TEE Based on Intel SGX HW"] = 2] = "TEE Based on Intel SGX HW";
    operatingEnvEnum[operatingEnvEnum["TEE Based on Intel ME/TXE HW"] = 3] = "TEE Based on Intel ME/TXE HW";
    operatingEnvEnum[operatingEnvEnum["TEE with GlobalPlatform TEE Protection Profile Certification"] = 4] = "TEE with GlobalPlatform TEE Protection Profile Certification";
    operatingEnvEnum[operatingEnvEnum["Windows 10 Virtualization-based Security"] = 5] = "Windows 10 Virtualization-based Security";
    operatingEnvEnum[operatingEnvEnum["Secure World of AMD PSP (Platform Security coProcessor)"] = 6] = "Secure World of AMD PSP (Platform Security coProcessor)";
    operatingEnvEnum[operatingEnvEnum["Trusted Platform Modules (TPMs) Complying to Trusted Computing Group specifications"] = 7] = "Trusted Platform Modules (TPMs) Complying to Trusted Computing Group specifications";
    operatingEnvEnum[operatingEnvEnum["Secure Element (SE)"] = 8] = "Secure Element (SE)";
})(operatingEnvEnum = exports.operatingEnvEnum || (exports.operatingEnvEnum = {}));
var VerificationMethodDescriptorUserVerificationMethodEnum;
(function (VerificationMethodDescriptorUserVerificationMethodEnum) {
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["error"] = 0] = "error";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["presence_internal"] = 1] = "presence_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["fingerprint_internal"] = 2] = "fingerprint_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["passcode_internal"] = 3] = "passcode_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["voiceprint_internal"] = 4] = "voiceprint_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["faceprint_internal"] = 5] = "faceprint_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["location_internal"] = 6] = "location_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["eyeprint_internal"] = 7] = "eyeprint_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["pattern_internal"] = 8] = "pattern_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["handprint_internal"] = 9] = "handprint_internal";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["none"] = 10] = "none";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["all"] = 11] = "all";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["passcode_external"] = 12] = "passcode_external";
    VerificationMethodDescriptorUserVerificationMethodEnum[VerificationMethodDescriptorUserVerificationMethodEnum["pattern_external"] = 13] = "pattern_external";
})(VerificationMethodDescriptorUserVerificationMethodEnum = exports.VerificationMethodDescriptorUserVerificationMethodEnum || (exports.VerificationMethodDescriptorUserVerificationMethodEnum = {}));
var G1CurveEnum;
(function (G1CurveEnum) {
    G1CurveEnum[G1CurveEnum["BN_P256"] = 0] = "BN_P256";
    G1CurveEnum[G1CurveEnum["BN_P638"] = 1] = "BN_P638";
    G1CurveEnum[G1CurveEnum["BN_ISOP256"] = 2] = "BN_ISOP256";
    G1CurveEnum[G1CurveEnum["BN_ISOP512"] = 3] = "BN_ISOP512";
})(G1CurveEnum = exports.G1CurveEnum || (exports.G1CurveEnum = {}));
